- name: Strawberry eko
  barcode: 7340734445548
  best_before: 10
  description: Fresh from the motherland
  fridge_temp: 8
  recommendations: Consistency might deteriorate, but it can still be used for many recipes
  plus_days_min: 12
  plus_days_max: 15

- name: Avocado
  barcode: 7340011445548
  best_before: 20
  description: Fresh avocados, directly from Mexico
  fridge_temp: 8
  recommendations: It's only the color, but it's still edible
  plus_days_min: 5
  plus_days_max: 10

- name: Red meat
  barcode: 73145721
  best_before: 30
  description: Red meat from local farms
  fridge_temp: 1
  recommendations: It's only the color, but it's still edible
  plus_days_min: 40
  plus_days_max: 45

- name: Coca Cola
  barcode: 7310070765987
  best_before: 30
  description: Carbonated soft drink
  fridge_temp: 5
  recommendations: Nobody knows if it can last forever
  plus_days_min: 30
  plus_days_max: 9999
