default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: foodexpiry_development

test:
  <<: *default
  database: foodexpiry_test

production:
  <<: *default
  database: foodexpiry_production
  username: postgres
  password: postgres
